### ISSUE TITLE
Need Help With Stream Passed to Reconnect

### ISSUE THREAD

**Issue by jmwright** [juliangruber/reconnect-net#4]
I'm new to reconnect-core and reconnect-net and am having some trouble. When I create a socket `var client = new net.Socket();` and pass it as the 'stream' argument in the client example, I get the following error even though I can see that it connects to the server.
```
[Error: This socket is closed.]
```
If I set up and pass an actual stream using the following code...
```javascript
var client = new stream.Stream();
client.writable = true
```
...I get the following error.
```
[TypeError: Object #<Stream> has no method 'write']
```
I can post my code, I just figured I'm missing something fundamental.

**Comment by jmwright** [comment]
To be clear, the 'socket is closed' error was being logged by me when I try to write to the client. It seems like the connect event never fires. I'll go ahead and post my code.
```javascript
var server = "192.168.1.11";
var port = 4242;

var client = new net.Socket();

reconnect(function(client) {
    client.on('connect', function(client) {
        console.log('CONNECTED TO: ' + server + ':' + port);

        // Write a message to the socket as soon as the client is connected, the server will receive it as message from the client 
        client.write('ready');

        lastMsgSent = new Date().getTime();
    });
    
    client.on('data', function(event) {
        var msg = event.data;
        if (msg === "clear") {
            console.log("Clear to Proceed");
        }
        else {
            console.log('DATA: ' + msg);
        }
    });

    client.on('disconnect', function(err)
    {
        // websocket is closed.
        console.log("Connection Closed");
    });

    client.on('error', function(err)
    {
        // websocket is closed.
        console.log("Connection Error");
    });
}).connect(port, server);
```

**Comment by juliangruber** [comment]
the problem is that your `client` reference isn't the one reconnect creates, it's your `net.Socket()`;

I'm assuming your code looks something like this:

```js
var client = net.Socket();

reconnect(function(client){
  // ...
}).connect(port, server);

doStuffWith(client);
```

while instead it should look like this:

```js
reconnect(function(client){
  doStuffWith(client);
}).connect(port, server);
```

You get a new `client` instance on every reconnection, that's why you need to react to the callback.

Feel free to reopen if you have further questions.

**Comment by jmwright** [comment]
@juliangruber 

From what I can see, my code doesn't try to call `doStuffWith(client)` outside of the reconnect function.

```javascript
var server = "192.168.1.11";
var port = 4242;

var client = new net.Socket();

reconnect(function(client) {
    client.on('connect', function(client) {
        console.log('CONNECTED TO: ' + server + ':' + port);

        // Write a message to the socket as soon as the client is connected, the server will receive it as message from the client 
        client.write('ready');

        lastMsgSent = new Date().getTime();
    });

    client.on('data', function(event) {
        var msg = event.data;
        if (msg === "clear") {
            console.log("Clear to Proceed");
        }
        else {
            console.log('DATA: ' + msg);
        }
    });

    client.on('disconnect', function(err)
    {
        // websocket is closed.
        console.log("Connection Closed");
    });

    client.on('error', function(err)
    {
        // websocket is closed.
        console.log("Connection Error");
    });
}).connect(port, server);
```

**Comment by juliangruber** [comment]
can you give me the exact output your code creates?

**Comment by jmwright** [comment]
I apologize. I did have one stray client call outside of reconnect that was causing the problem. I thought I had pulled all that code inside. Thanks for the help.

**Comment by sveip** [comment]
Short related question.

Is it ok to pass the `_connection` key from the reconnect object and write to that from elsewhere in my code?

I'm doing something like this, which seems to work
```javascript
    var re = new reconnect(function(client) {
      client.on('data', function (data) {
        "do stuff"
      });
    }).connect(socketPort, socketHost, function () {
      callback(createConnection(re._connection, requests));
    }).on('error', function (e) {
      "handle error"
    });
```

Maybe there is a better way, but I have not found any examples on how to use the clinet in this way. If you now any projects that use `reconnect-net` that I can have a look at, please let me know.

Kind regards, Peter

**Comment by juliangruber** [comment]
```js
...
.on('connect', function (connection) {
  // this is the `connection` object you want to use
})`
